export const FrankieOneEntityTypeMap = {
  SOLE_TRADER: 'INDIVIDUAL',
  PARTNERSHIP: 'INDIVIDUAL', //TODO: entity type for partnership?
  COMPANY: 'ORGANISATION',
  INDIVIDUAL: 'INDIVIDUAL',
  TRUST: 'TRUST',
  NOT_FOR_PROFIT: 'ORGANISATION',
  SELF_MANAGED_SUPER_FUND: 'TRUST',
};
