nodeLinker: node-modules
pnpMode: "loose"

npmScopes:
  apptractive:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
